<?php
/**
 * Skript pro vytváření RSS z nabídky serveru Sbazar - pomocné funkce.
 *
 * @author Ondřej Doněk, <ondrejd@gmail.com>
 */

?>
<!DOCTYPE html>
<html lang="cs">
    <head>
        <meta charset="utf-8">
        <title>Administrace crawlera pro Sbazar</title>
    </head>
    <body class="sc sc-admin">
        <div class="wrap">
            <div class="header">
                <h1>Administrace crawlera pro Sbazar.cz</h1>
            </div>
            <div class="page">
                <form class="form" method="POST">
                    <!-- XXX Hidden security field -->
                    <div class="form-row">
                        Nastavení kategorie
                    </div>
                    <div class="form-row">
                        Nastavení ceny od-do
                    </div>
                    <div class="form-row">
                        Nastavení města
                    </div>
                    <div class="form-row">
                        Řazení (defaultně a napevno od nejnovějších)
                    </div>
                </form>
            </div>
        </div>
    </body>
</html>
