<?php
/**
 * Skript pro vytváření RSS z nabídky serveru Sbazar - pomocné funkce.
 *
 * @author Ondřej Doněk, <ondrejd@gmail.com>
 */

?>
<!DOCTYPE html>
<html lang="cs">
    <head>
        <meta charset="utf-8">
        <title>Administrace crawlera pro Sbazar</title>
    </head>
    <body class="sc sc-admin">
        <div class="wrap">
            <div class="header">
                <h1>Administrace crawlera pro Sbazar.cz</h1>
            </div>
            <div class="page">
                <p>Podle polí formuláře níže bude vygenerována URL na Sbazar, ze které se pak vygeneruje RSS soubor s inzeráty. Aktuálně použitá URL je <code><?php echo $current_url ?></code>.</p>
                <form class="form" method="POST">
                    <div class="form-row">
                        <label for="sc-category">Kategorie:</label>
                        <select id="sc-category" name="sc_category" value="<?php echo $category ?>">
                            <option value=""<?php empty( $category ) ? ' selected' : '' ?>>Žádná</option>
                            <?php foreach( \sbazar_crawler\get_categories() as $cat => $cat_url ) : ?>
                            <option value="<?php echo $cat_url ?>"<?php ( $cat_url === $category ) ? ' selected' : '' ?>><?php echo $cat ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                    <div class="form-row">
                        <label for="sc-price_from">Cena od:</label>
                        <input id="sc-price_form" name="sc_price_form" type="number">
                        <label for="sc-price_from"> do: </label>
                        <input id="sc-price_to" name="sc_price_to" type="number">
                    </div>
                    <div class="form-row">
                        <label for="sc-town">PSČ:</label>
                        <input id="sc-town" name="sc_town" type="text" value="<?php echo $town ?>" style="width: 80px;">
                    </div>
                    <div class="form-row form-row--submit_buttons">
                        <input name="sc_submit" type="submit" value="Uložit">
                        <input name="sc_reset" type="reset" value="Zrušit">
                    </div>
                </form>
            </div>
        </div>
    </body>
</html>
