<?php
/**
 * Skript pro vytváření RSS z nabídky serveru Sbazar - šablona pro administraci při špatném heslu.
 *
 * @author Ondřej Doněk, <ondrejd@gmail.com>
 */

?>
<!DOCTYPE html>
<html lang="cs">
    <head>
        <meta charset="utf-8">
        <title>Chybné přihlášení do administrace crawlera pro Sbazar</title>
    </head>
    <body class="sc sc-admin">
        <div class="wrap">
            <div class="header">
                <h1>Administrace crawlera pro Sbazar.cz</h1>
            </div>
            <div class="page">
                <p class="notice notice-error">Zadali jste nesprávné heslo! Pokud si myslíte, že jste oprávněný uživatel a jen jste heslo zapoměli, napište administrátorovi tohoto serveru.</p>
            </div>
        </div>
    </body>
</html>
