<?php
/**
 * Skript pro vytváření RSS z nabídky serveru Sbazar - šablona pro administraci při špatném heslu.
 *
 * @author Ondřej Doněk, <ondrejd@gmail.com>
 */

?>
<!DOCTYPE html>
<html lang="cs">
    <head>
        <meta charset="utf-8">
        <title>Chybné přihlášení do administrace crawlera pro Sbazar</title>
        <style type="text/css">
html { margin:0; padding:0; font-family:"HelveticaNeue", "Helvetica Neue", Helvetica, Arial, sans-serif; color:#222; -webkit-user-select:none; -ms-user-select:none; -moz-user-select:none; user-select:none; }
body { margin:0; padding:0; background:0 0; }
a { outline:0; text-decoration:none; }
h1 { font-size:3.2em; line-height:1.25; margin-top:2em; margin-bottom:1em; font-weight:300; text-align:center; }
h2 { font-size:2.0em; line-height:1.05; margin-top:1em; margin-bottom:1em; font-weight:300; text-align:center; }
code { font-size:105%; }
.wrap { margin:0; padding:0; width:100%; }
.page { margin:0 10em 0 10em; padding:0; width:auto; }
.page p { text-align:center; }
.form-row { padding:.2em 0; }
.form-row--submit_buttons { padding-top:1em; }
form #sc-price_form, form #sc-price_to, form #sc-town { width:80px; }
form label { display:inline-block; width:100px; }
form label[for="sc-price_to"] { width:auto; }
        </style>
    </head>
    <body class="sc sc-admin">
        <div class="wrap">
            <div class="header">
                <h1>Administrace crawlera pro Sbazar.cz</h1>
            </div>
            <div class="page">
                <h2>Zadali jste nesprávné heslo!</h2>
                <p>Pokud si myslíte, že jste oprávněný uživatel a jen jste heslo zapoměli, napište administrátorovi tohoto serveru.</p>
            </div>
        </div>
    </body>
</html>
